# URL-ing
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

# Folder structure
source: . # default value
destination: _site # default value

# Markdown
markdown: kramdown

# Collections

# Default front matters
defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post

# Pagination
paginate: 5

# Plugins (formerly `gems`)
plugins:
  - jekyll-paginate
