# CircleCI 2.0
version: 2

# Default config shared by all jobs
defaults: &defaults
  working_directory: ~/repo

general:
  branches:
    ignore:
      - gh-pages

jobs:
  # Building the website
  build:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      # Dependencies
      - restore_cache:
          keys:
            - tutorial-website-dependencies-{{ checksum "Gemfile.lock" }}
            - tutorial-website-dependencies-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: tutorial-website-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ${BUNDLE_PATH}
      # Building
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - persist_to_workspace:
          root: ./
          paths:
            - tutorial-website/_site
      # Deploy
      - run:
          name: Deploying Github page
          command: ./circleci/deploy-ghpages.sh
