# CircleCI 2.0
version: 2

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy

jobs:
  # Building the website
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.5
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      # Dependencies
      - restore_cache:
          keys:
            - tutorial-website-dependencies-v1-{{ checksum "Gemfile.lock" }}
            - tutorial-website-dependencies-v1-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: tutorial-website-dependencies-v1-{{ checksum "Gemfile.lock" }}
          paths:
            -  ~/repo/vendor/bundle
      # Building
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - run: mkdir ~/artifacts
      - persist_to_workspace:
          root: ./
          paths:
            - tutorial-website/_site

  deploy:
    working_directory: ~/
    machine: 
      enabled: true
    steps:
      - run: pwd
      - run: ls
      - run: ls ~/artifacts
      # # Deploy
      # # https://github.com/Villanuevand/deployment-circleci-gh-pages
      # - run:
      #     name: Deploying Github page
      #     command: |
      #       chmod +x ~/repo/.circleci/deploy-ghpages.sh
      #       ~/repo/.circleci/deploy-ghpages.sh tutorial-website/_site
