# CircleCI 2.0
version: 2

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

jobs:
  # Building the website
  build:
    working_directory: ~/repo/
    docker:
      - image: circleci/ruby:2.5
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      # Dependencies
      - restore_cache:
          keys:
            - tutorial-website-dependencies-v1-{{ checksum "Gemfile.lock" }}
            - tutorial-website-dependencies-v1-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: tutorial-website-dependencies-v1-{{ checksum "Gemfile.lock" }}
          paths:
            -  ~/repo/vendor/bundle
      # Building
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory.
          # This is a directory on the container which is  taken to be the root
          # directory of the workspace.
          root: ./
          paths:
            - tutorial-website/_site
            - .circleci/deploy-ghpages.sh

  deploy:
    working_directory: ~/
    docker:
      - image: buildpack-deps:trusty
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo/
      - run: ls
      - run: ls ~
      - run: ls ~/repo/tutorial-website
      - run: ls ~/repo/tutorial-website/_site
      - run: ls ~/repo/.circle-ci
      # # Deploy
      # # https://github.com/Villanuevand/deployment-circleci-gh-pages
      # - run:
      #     name: Deploying Github page
      #     command: |
      #       chmod +x ~/repo/.circleci/deploy-ghpages.sh
      #       ~/repo/.circleci/deploy-ghpages.sh tutorial-website/_site
