# CircleCI 2.0
version: 2

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

jobs:
  # Building the website
  build:
    working_directory: /tmp/repo/
    docker:
      - image: circleci/ruby:2.5
    environment:
      BUNDLE_PATH: repo/vendor/bundle
    steps:
      - checkout
      # Dependencies
      - restore_cache:
          keys:
            - tutorial-website-dependencies-v1-{{ checksum "Gemfile.lock" }}
            - tutorial-website-dependencies-v1-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: tutorial-website-dependencies-v1-{{ checksum "Gemfile.lock" }}
          paths:
            -  repo/vendor/bundle
      # Building
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: tutorial-website
          paths:
            - _site
      - run: pwd
      - run: ls
      - run: ls ~
      - run: ls tutorial-website
      - run: ls tutorial-website/_site

  deploy:
    working_directory: /tmp
    docker:
      - image: buildpack-deps:trusty
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/repo/tutorial-website
      - run: pwd
      - run: ls
      - run: ls /tmp/repo
      - run: ls /tmp/repo/tutorial-website
      - run: ls /tmp/repo/tutorial-website/_site
      # - run: ls ~/artifacts
      # # Deploy
      # # https://github.com/Villanuevand/deployment-circleci-gh-pages
      # - run:
      #     name: Deploying Github page
      #     command: |
      #       chmod +x ~/repo/.circleci/deploy-ghpages.sh
      #       ~/repo/.circleci/deploy-ghpages.sh tutorial-website/_site
